<!-- src/lib/components/docs/sections/go/DocGoPackageLayout.svelte -->
<script lang="ts">
  import CodeBlock from '$lib/components/CodeBlock.svelte';
  const layout = `mdix-go/
├── dixscript.go           # Load*, NewBuilder, Version — top-level facade
├── database.go            # Database type — all typed getters
├── builder.go             # Builder type — Set*, Save, ToString
├── converter.go           # Convert.ToJSON / FromJSON / ToToml / Format / Minify
├── query.go               # Query[T] — generic LINQ-style helpers
├── schema.go              # SchemaBuilder — Require*/Optional* validation
├── merge.go               # MergeSources / MergeSourcesWeighted
├── watch.go               # EnableHotReload / OnReloaded / OnReloadFailed
├── types.go               # HexColor, Blob, MdixRegex, MdixDate, MdixTimestamp, ValueType
├── errors.go              # MdixError, ErrorKind constants
├── internal/
│   ├── ffi.go             # all cgo declarations — the only file with unsafe
│   ├── include/mdix_ffi.h # generated by cbindgen — do not edit
│   └── lib/                # native libs — populated by CI or local cargo build
└── examples/
    ├── basic/main.go
    └── game_config/main.go`;
</script>

<div class="doc-page">
  <h1>Package Layout</h1>
  <p class="page-lead">Part of the <a href="#go-api">Go Runtime API</a>.</p>
  <CodeBlock code={layout} lang="text" />
</div>
